server {
  listen 80;
  server_name envra.lengziyu.cn;
  client_max_body_size 30m;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name envra.lengziyu.cn;
  client_max_body_size 30m;

  ssl_certificate /etc/letsencrypt/live/envra.lengziyu.cn/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/envra.lengziyu.cn/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  root /opt/apps/envra.lengziyu.cn/dist;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \\.(?:css|js|mjs|map|jpg|jpeg|gif|png|svg|ico|webp|woff2?|ttf)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
    try_files $uri =404;
  }
}
